### PR TITLE
Add month and year

### PR DESCRIPTION
**Pull request by thiamsantos**
Added the functions below:
 - `month`: function to calculate seconds since beginning of the month
 - `year`: function to calculate seconds since beginning of the year

### CODE REVIEW

**Comment by charlike** [comment]
Hey thanks for that pull request. I'm totally okey with it, @jonschlinkert you?

**Review by tunnckoCore — APPROVED** [review]

**Comment by thiamsantos** [comment]
Any thoughts @jonschlinkert?

**Comment by charlike** [comment]
I can merge, it's not a problem, but i won't be able to publish it.

@thiamsantos probably this would work for you too :)

**Comment by thiamsantos** [comment]
Thanks @charlike!

**Pull request merged**
